sudo: required

services:
  - docker

language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cracklib-runtime libcrack2-dev strace
  - gem install bundler
  - docker pull ruby:2.2.4-onbuild

bundler_args: --without debugger

script:
  - bundle exec rake test
  - bundle exec rspec

notifications:
  email:
  - ngiger@ywesee.com

rvm:
  - ruby-head
  - 2.2.4
  - 2.1.7
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
