language: ruby
before_install:
  - gem install bundler

bundler_args: --without debugger

script:
  - bundle exec rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.7
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
