language: ruby
before_install:
  - gem install bundler

install:
  - bundle install --without yus_runtime

script:
  - rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
