language: ruby
before_install:
  - gem install bundler

# we install minitest via  gem install and not bundle install
# because Ruby 1.9/2.0 seem to mess up the rubygems installation
# see http://docs.seattlerb.org/minitest/ (Install)
before_script:
  - gem install minitest
  - bundle install --without yus_runtime

script:
  - rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
