# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Devenv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
  # see https://github.com/ruby/setup-ruby
    strategy:
    strategy:
      matrix:
        ruby-version: ['3.0', 3.1, 3.2, 3.3, 3.4, 'head']
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Test with Ruby ${{ matrix.ruby-version }}
        run: |
          devenv --option languages.ruby.enable:bool true \
                 --option languages.ruby.version:string ${{ matrix.ruby-version }} \
                 test
